<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="DotNet.ReproducibleBuilds.Isolated" Version="2.0.2" />
  <PropertyGroup>
    <TargetFramework>net10.0-windows8.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Foreman</RootNamespace>
    <AssemblyName>Foreman</AssemblyName>
    <ApplicationVisualStyles>true</ApplicationVisualStyles>
    <ApplicationUseCompatibleTextRendering>true</ApplicationUseCompatibleTextRendering>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AssemblyTitle>Foreman 2</AssemblyTitle>
    <Description>Flowchart generation program for Factorio</Description>
    <Company></Company>
    <Product>Foreman</Product>
    <Copyright>Copyright ©2021 Daniel Kotes; ©2014 Nick Powell</Copyright>
    <VersionPrefix>99.99.99</VersionPrefix>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <ApplicationManifest>Properties\app.manifest</ApplicationManifest>
    <ApplicationIcon>Foreman2.ico</ApplicationIcon>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <SupportedOSPlatformVersion>8.0</SupportedOSPlatformVersion>
    <Platforms>AnyCPU;x64;x86</Platforms>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="ForemanTest" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="Google.OrTools" Version="9.15.6755" />
    <PackageReference Include="Google.Protobuf" Version="3.34.1" />
    <PackageReference Include="ZstdSharp.Port" Version="0.8.8" />
    <PackageReference Include="DotNet.ReproducibleBuilds" Version="2.0.2" PrivateAssets="All"/>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Controls\DataObjectCheckedListBox.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\CustomProgressBar.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\EditRecipePanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\EditFlowPanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\ChooserIconGrid.cs">
      <SubType>Component</SubType>
    </Compile>
    <EmbeddedResource Update="Controls\ChooserIconGrid.resx">
      <DependentUpon>ChooserIconGrid.cs</DependentUpon>
    </EmbeddedResource>
    <Compile Update="Controls\IRChooserPanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <EmbeddedResource Update="Controls\IRChooserPanel.resx">
      <DependentUpon>IRChooserPanel.cs</DependentUpon>
    </EmbeddedResource>
    <Compile Update="Controls\RecipePanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\RecipeToolTip.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\SyncListView.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="ProductionGraphView\ProductionGraphViewer.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <None Update="App.config" />
    <None Update="baseCustom.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Presets\Factorio 2.0 Space Age.dat">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Presets\Factorio 2.0 Space Age.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Presets\Factorio 2.0 Space Age.pjson">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Presets\Factorio 2.0 Vanilla.dat">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Presets\Factorio 2.0 Vanilla.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Presets\Factorio 2.0 Vanilla.pjson">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Foreman2.ico" />
    <Content Include="Graphics\BurnerGeneratorIcon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Graphics\ElectricityIcon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Graphics\ErrorIcon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Graphics\ExtraGroupIcon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Graphics\HeatIcon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Graphics\PlantAssembler.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Graphics\PlayerAssembler.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Graphics\RocketAssembler.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Graphics\SpoilAssembler.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Graphics\UnknownIcon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Licences.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
	<Content Include="Mods\**\*.*">
	  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	</Content>
  </ItemGroup>
</Project>
