//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foreman.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentPresetName {
            get {
                return ((string)(this["CurrentPresetName"]));
            }
            set {
                this["CurrentPresetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultModuleOption {
            get {
                return ((int)(this["DefaultModuleOption"]));
            }
            set {
                this["DefaultModuleOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MinorGridlines {
            get {
                return ((int)(this["MinorGridlines"]));
            }
            set {
                this["MinorGridlines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MajorGridlines {
            get {
                return ((int)(this["MajorGridlines"]));
            }
            set {
                this["MajorGridlines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AltGridlines {
            get {
                return ((bool)(this["AltGridlines"]));
            }
            set {
                this["AltGridlines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowHidden {
            get {
                return ((bool)(this["ShowHidden"]));
            }
            set {
                this["ShowHidden"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IgnoreAssemblerStatus {
            get {
                return ((bool)(this["IgnoreAssemblerStatus"]));
            }
            set {
                this["IgnoreAssemblerStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DynamicLineWidth {
            get {
                return ((bool)(this["DynamicLineWidth"]));
            }
            set {
                this["DynamicLineWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RecipeNameOnlyFilter {
            get {
                return ((bool)(this["RecipeNameOnlyFilter"]));
            }
            set {
                this["RecipeNameOnlyFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LevelOfDetail {
            get {
                return ((int)(this["LevelOfDetail"]));
            }
            set {
                this["LevelOfDetail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultAssemblerOption {
            get {
                return ((int)(this["DefaultAssemblerOption"]));
            }
            set {
                this["DefaultAssemblerOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultRateUnit {
            get {
                return ((int)(this["DefaultRateUnit"]));
            }
            set {
                this["DefaultRateUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSaveFileLocation {
            get {
                return ((string)(this["LastSaveFileLocation"]));
            }
            set {
                this["LastSaveFileLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowRecipeToolTip {
            get {
                return ((bool)(this["ShowRecipeToolTip"]));
            }
            set {
                this["ShowRecipeToolTip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowUnavailable {
            get {
                return ((bool)(this["ShowUnavailable"]));
            }
            set {
                this["ShowUnavailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LockedRecipeEditorPosition {
            get {
                return ((bool)(this["LockedRecipeEditorPosition"]));
            }
            set {
                this["LockedRecipeEditorPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int NodeCountForSimpleView {
            get {
                return ((int)(this["NodeCountForSimpleView"]));
            }
            set {
                this["NodeCountForSimpleView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseRecipeBWfilters {
            get {
                return ((bool)(this["UseRecipeBWfilters"]));
            }
            set {
                this["UseRecipeBWfilters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowWarningArrows {
            get {
                return ((bool)(this["ShowWarningArrows"]));
            }
            set {
                this["ShowWarningArrows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowErrorArrows {
            get {
                return ((bool)(this["ShowErrorArrows"]));
            }
            set {
                this["ShowErrorArrows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AbbreviateSciPacks {
            get {
                return ((bool)(this["AbbreviateSciPacks"]));
            }
            set {
                this["AbbreviateSciPacks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RoundAssemblerCount {
            get {
                return ((bool)(this["RoundAssemblerCount"]));
            }
            set {
                this["RoundAssemblerCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableExtraProductivityForNonMiners {
            get {
                return ((bool)(this["EnableExtraProductivityForNonMiners"]));
            }
            set {
                this["EnableExtraProductivityForNonMiners"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowDisconnectedArrows {
            get {
                return ((bool)(this["ShowDisconnectedArrows"]));
            }
            set {
                this["ShowDisconnectedArrows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultNodeDirection {
            get {
                return ((int)(this["DefaultNodeDirection"]));
            }
            set {
                this["DefaultNodeDirection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FlagOUSuppliedNodes {
            get {
                return ((bool)(this["FlagOUSuppliedNodes"]));
            }
            set {
                this["FlagOUSuppliedNodes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowOUSuppliedArrows {
            get {
                return ((bool)(this["ShowOUSuppliedArrows"]));
            }
            set {
                this["ShowOUSuppliedArrows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IconsOnlyView {
            get {
                return ((bool)(this["IconsOnlyView"]));
            }
            set {
                this["IconsOnlyView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int IconsSize {
            get {
                return ((int)(this["IconsSize"]));
            }
            set {
                this["IconsSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SimplePassthroughNodes {
            get {
                return ((bool)(this["SimplePassthroughNodes"]));
            }
            set {
                this["SimplePassthroughNodes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ArrowsOnLinks {
            get {
                return ((bool)(this["ArrowsOnLinks"]));
            }
            set {
                this["ArrowsOnLinks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ForemanVersion {
            get {
                return ((int)(this["ForemanVersion"]));
            }
            set {
                this["ForemanVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SmartNodeDirection {
            get {
                return ((bool)(this["SmartNodeDirection"]));
            }
            set {
                this["SmartNodeDirection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W")]
        public global::System.Windows.Forms.Keys KeyUpCode {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyUpCode"]));
            }
            set {
                this["KeyUpCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public global::System.Windows.Forms.Keys KeyDownCode {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyDownCode"]));
            }
            set {
                this["KeyDownCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public global::System.Windows.Forms.Keys KeyLeftCode {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyLeftCode"]));
            }
            set {
                this["KeyLeftCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D")]
        public global::System.Windows.Forms.Keys KeyRightCode {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyRightCode"]));
            }
            set {
                this["KeyRightCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int KeyScrollRatio {
            get {
                return ((int)(this["KeyScrollRatio"]));
            }
            set {
                this["KeyScrollRatio"] = value;
            }
        }
    }
}
