name: Snapshot Pipeline

on:
  push:
    branches-ignore: ['github']
    tags-ignore: ['*']
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  Windows:
    name: Windows Snapshot
    if: ${{ !contains(github.event.head_commit.message, '[CI Skip]') }}
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.2
        with:
          ref: ${{github.ref}}
          fetch-depth: 0
      - name: Get Tag Version
        id: tag
        uses: actions/github-script@v9
        with:
          script: |
            let ret = '';
            const options = {};
            options.listeners = {
              stdout: (data) => {
                ret += data.toString();
              }
            };
            await exec.exec('git', ['describe'], options);
            return ret.substring(1).split('-')[0].trim()
          result-encoding: string
      - name: Install .NET
        uses: actions/setup-dotnet@v5.2.0
        with:
          dotnet-version: '10.x'
      - name: Restore Dependencies
        run: dotnet restore -r win-x64
      - name: Verify Formatting
        run: dotnet format --verify-no-changes
      - name: Build Foreman Snapshot
        run: dotnet build Foreman -p:VersionPrefix=${{steps.tag.outputs.result}} -p:VersionSuffix=SNAPSHOT --configuration Release -r win-x64
      - name: Test Foreman
        run: dotnet test --configuration Release -r win-x64
        timeout-minutes: 1
      - name: Package Foreman (Self-Contained)
        run: dotnet publish Foreman --sc -p:PublishSingleFile=true -o distsc -p:VersionPrefix=${{steps.tag.outputs.result}} -p:VersionSuffix=SNAPSHOT -p:IncludeNativeLibrariesForSelfExtract=true --configuration Release -r win-x64
      - name: Package Foreman (.NET Dependent)
        run: dotnet publish Foreman --no-self-contained -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o dist -p:VersionPrefix=${{steps.tag.outputs.result}} -p:VersionSuffix=SNAPSHOT --configuration Release -r win-x64
      - name: Archive Foreman (Self-Contained)
        uses: actions/upload-artifact@v4
        with:
          name: ForemanSC-${{github.sha}}
          path: distsc/*
          if-no-files-found: error
      - name: Archive Foreman (.NET Dependent)
        uses: actions/upload-artifact@v4
        with:
          name: Foreman-${{github.sha}}
          path: dist/*
          if-no-files-found: error

